### PR TITLE
Fix #1752 Bump entity version

### LINKED ISSUE #1752: org.terracotta.runnel.utils.LimitReachedException when running 3.3 server and 3.2.1 client
When running the 3.3.0-SNAPSHOT server with a 3.2.1-SNAPSHOT client, the server throws a LimitReachedException when the client attempts to connect - instead we should see an exception that the entity versions do not match

[exception.txt](https://github.com/ehcache/ehcache3/files/668651/exception.txt)
[terracotta-server.txt](https://github.com/ehcache/ehcache3/files/668652/terracotta-server.txt)
[tc-config.txt](https://github.com/ehcache/ehcache3/files/668653/tc-config.txt)

### PR DESCRIPTION
**Pull request by ljacomet**
This represents incompatibility - should have been done when the
configuration on create happened ideally.

### CODE REVIEW

File: clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java [hunk 1]
```diff
@@ -60,7 +61,7 @@ public static void waitForActive() throws Exception {
   public void testAbsentEntityRetrievalFails() throws Throwable {
     Connection client = CLUSTER.newConnection();
     try {
-      EntityRef<EhcacheClientEntity, ClusteredTierManagerConfiguration> ref = client.getEntityRef(EhcacheClientEntity.class, 1, "testAbsentEntityRetrievalFails");
+      EntityRef<EhcacheClientEntity, ClusteredTierManagerConfiguration> ref = client.getEntityRef(EhcacheClientEntity.class, EhcacheEntityVersion.ENTITY_VERSION, "testAbsentEntityRetrievalFails");
```
Comment (henri-tremblay) [inline clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java]: Can you please extract a method and retrieve the test name using a Rule?
