### PR TITLE
Issue #1108 Prevent client stall on CacheManager.close

### LINKED ISSUE #1108: CacheManager.close() indefinitely waits when closing
In our system tests, if at the end we shutdown the server before the cache manager, the the application blocks because the CM cannot be closed.

Groovy code to reproduce:

```
package com.terracottatech.issues

import org.ehcache.PersistentCacheManager
import org.ehcache.clustered.client.config.builders.ClusteringServiceConfigurationBuilder
import org.ehcache.config.builders.CacheManagerBuilder

CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
    .with(ClusteringServiceConfigurationBuilder.cluster(URI.create('terracotta://localhost:9510').resolve("/MyCacheManagerName?auto-create"))
    .defaultServerResource("primary-server-resource"))
cacheManager = clusteredCacheManagerBuilder.build(false)
cacheManager.init()
println "Press a key to close..."
System.in.read()
cacheManager.close()
```

1. Start the server
2. Run the code
3. Stop te server
4. Press a key to continue to `cacheManager.close()`

It blocks.

Stack trace:

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:141)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:42)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:164)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:155)
	  at org.terracotta.voltron.proxy.client.VoltronProxyInvocationHandler.invoke(VoltronProxyInvocationHandler.java:109)
	  at com.sun.proxy.$Proxy7.delist(Unknown Source:-1)
	  at org.terracotta.consensus.CoordinationService.delist(CoordinationService.java:176)
	  at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.abandonLeadership(EhcacheClientEntityFactory.java:78)
	  at org.ehcache.clustered.client.internal.service.DefaultClusteringService.stop(DefaultClusteringService.java:182)
	  at org.ehcache.core.internal.service.ServiceLocator.stopAllServices(ServiceLocator.java:350)
	  at org.ehcache.core.EhcacheManager.close(EhcacheManager.java:608)
	  at org.ehcache.CacheManager$close$0.call(Unknown Source:-1)
	  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	  at com.terracottatech.issues.EhcacheIssue.run(EhcacheIssue.groovy:14)
```

### PR DESCRIPTION
**Pull request by cljohnso**
This commit changes the behavior of DefaultClusteringService.close to
avoid Entity calls that might result in an interaction with the server.
Server interactions made when the server is disconnected can result in
operation stalls which are not resolved until the server returns to
service.  This kind of stall makes little sense when closing a
CacheManager.

This commit also adds an integration-test test case to reproduce the
symptoms of the issue.  TestLoggingService is added to enable
client-side logging from integration-test unit tests.

Fixes #1108.

### CODE REVIEW

**Comment by cljohnso** [comment]
This PR does nothing to address the general issue of operation stalls due to a client/server disconnect -- this one simply alters `DefaultClusteringService.close` behavior to avoid methods which interact with the server.

File: clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+    cluster.getClusterControl().tearDown();
+
+    Future<Void> future = interruptAfter(2, TimeUnit.SECONDS);
+    try {
+      cacheManager.close();
+    } finally {
+      future.cancel(true);
+    }
+
+    // TODO: Add assertion for successful CacheManager.init() following cluster restart (https://github.com/Terracotta-OSS/galvan/issues/30)
```
Comment (cljohnso) [inline clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java]: This test should be amended once functionality suggested by Terracotta-OSS/galvan#30 is available.

File: clustered/integration-test/src/test/java/com/tc/logging/TestLoggingService.java [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+ */
+
+package com.tc.logging;
+
+import java.net.URI;
+
+/**
+ * A Terracotta logger writing to {@code System.out}.
+ */
+public class TestLoggingService implements TCLoggingService {
```
Comment (cljohnso) [inline clustered/integration-test/src/test/java/com/tc/logging/TestLoggingService.java]: This was added to get client logging from `integration-test` module tests.  Without this, the client logging winds up in the bit bucket _or_ requires a JDK logging configuration.
