### PR TITLE
Fix #2214 : Handle very large puts that may not fit the cache

### LINKED ISSUE #2204: IndexOutOfBoundException during passive replication application
`ChainReplicationMessage.getResult()` behaves badly when the chain it's being asked to replicate is empty.  This can happen when there are multiple clients accessing the system due to cross segment eviction.  There are a number of ways of fixing this, and there is also some overdue yak shaving that can occur in this area.

### LINKED ISSUE #2214: A *very* large put can bring down the active and/or passive server.
If the OffHeapServerStore legitimately throws an OversizeMappingException (because the value presented is too large to fit in the offheap resourcre configured) then the propagating OversizeMappingException will cause the server to terminate.  Although this scenario is highly unlikely in a typical configuration we should prevent propagation of this exception and instead act as if the value was immediately evicted.

### PR DESCRIPTION
**Pull request by rkavanap**
Avoid the effect of clearing the cache if the user tries to put an object that is bigger than the cache.

### CODE REVIEW

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java [hunk 1]
```diff
@@ -175,4 +178,11 @@ public int getReprobeLength() {
 
     throw new UnsupportedOperationException("Not supported yet.");
   }
+
+  private void checkPayLoadSize(ByteBuffer payLoad) {
+    if (payLoad.remaining() > pageSource.getPool().getSize()) {
+      throw new OversizeMappingException("Payload (" + payLoad.remaining() +
```
Comment (henri-tremblay) [inline clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: Why is this exception not thrown to the client? Resilience strategy?

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java [hunk 2]
```diff
@@ -66,11 +67,13 @@ public Chain get(long key) {
 
   @Override
   public void append(long key, ByteBuffer payLoad) {
+    checkPayLoadSize(payLoad);
```
Comment (henri-tremblay) [inline clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: I will let someone else (@chrisdennis) confirm but it feels weird that it's not the server that is responsible to verify this. Also, why can't it happen on `replaceAtHead`, and `put`?

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java (hunk 1 above)
Comment (rkavanap) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: yes..default resiliency strategy also evicts in the correct order so did not do an explicit server side eviction, although again I will wait for @chrisdennis to comment.

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java (hunk 2 above)
Comment (rkavanap) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: @henri-tremblay this is just to prevent a very large put (larger than the cache) act like a cache.clear().. Ofcourse, we may still have a very large put that fits the cache that may evict everything else..but that may be a legitimate thing..

Since we prevent such chains being formed, replaceAtHead (which is not a direct client action) and put (passive only) should not have such large single chain that crosses the pool size on the active and passive.

It is debatable whether to put this check on client side or server side. One advantage of server side is we have got all the overhead in the payload and it is easier to check pool size.

Comment (henri-tremblay) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: The advantage of client-side you mean?

Comment (rkavanap) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: no currently it is server side.. as ServerStoreImpl is on server side..

Comment (henri-tremblay) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: Oh dear... Totally misread. Sorry. All good then.

File: clustered/integration-test/src/test/java/org/ehcache/clustered/OversizedCacheOpsTest.java [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+      + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">2</ohr:resource>"
+      + "</ohr:offheap-resources>" +
+      "</config>\n";
+
+  @ClassRule
+  public static Cluster CLUSTER =
+      newCluster().in(new File("build/cluster")).withServiceFragment(RESOURCE_CONFIG).build();
+
+  @BeforeClass
+  public static void waitForActive() throws Exception {
```
Comment (chrisdennis) [inline clustered/integration-test/src/test/java/org/ehcache/clustered/OversizedCacheOpsTest.java]: This *shouldn't* be necessary... I'd rather avoid using it when it's not necessary.

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java (hunk 1 above)
Comment (chrisdennis) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: I *think* this is okay.  It's probably not how I would have done it, but I think it's valid.

**Comment by rkavanap** [comment]
@henri-tremblay done with all review comments. Pls take a look and approve if found ok..

File: clustered/integration-test/src/test/java/org/ehcache/clustered/OversizedCacheOpsTest.java [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+    final PersistentCacheManager cacheManager = clusteredCacheManagerBuilder.build(false);
+    cacheManager.init();
+
+    try {
+      CacheConfiguration<Long, String> config = CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
+          ResourcePoolsBuilder.newResourcePoolsBuilder()
+              .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 1, MemoryUnit.MB))).build();
+
+      Cache<Long, String> cache = cacheManager.createCache("clustered-cache", config);
+      cache.put(1L, "The one");
```
[the remark this answers is not in the document]
Comment (rkavanap) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/OversizedCacheOpsTest.java]: I have removed the asserts.. But as discussed, I need to put multiple entries to assert that other entries are not evicted when a large entry that does not fit is added.

**Comment by rkavanap** [comment]
test this please
