### PR TITLE
Issue #1158 Implement Ehcache operation timeouts

### LINKED ISSUE #1108: CacheManager.close() indefinitely waits when closing
In our system tests, if at the end we shutdown the server before the cache manager, the the application blocks because the CM cannot be closed.

Groovy code to reproduce:

```
package com.terracottatech.issues

import org.ehcache.PersistentCacheManager
import org.ehcache.clustered.client.config.builders.ClusteringServiceConfigurationBuilder
import org.ehcache.config.builders.CacheManagerBuilder

CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
    .with(ClusteringServiceConfigurationBuilder.cluster(URI.create('terracotta://localhost:9510').resolve("/MyCacheManagerName?auto-create"))
    .defaultServerResource("primary-server-resource"))
cacheManager = clusteredCacheManagerBuilder.build(false)
cacheManager.init()
println "Press a key to close..."
System.in.read()
cacheManager.close()
```

1. Start the server
2. Run the code
3. Stop te server
4. Press a key to continue to `cacheManager.close()`

It blocks.

Stack trace:

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:141)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:42)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:164)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:155)
	  at org.terracotta.voltron.proxy.client.VoltronProxyInvocationHandler.invoke(VoltronProxyInvocationHandler.java:109)
	  at com.sun.proxy.$Proxy7.delist(Unknown Source:-1)
	  at org.terracotta.consensus.CoordinationService.delist(CoordinationService.java:176)
	  at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.abandonLeadership(EhcacheClientEntityFactory.java:78)
	  at org.ehcache.clustered.client.internal.service.DefaultClusteringService.stop(DefaultClusteringService.java:182)
	  at org.ehcache.core.internal.service.ServiceLocator.stopAllServices(ServiceLocator.java:350)
	  at org.ehcache.core.EhcacheManager.close(EhcacheManager.java:608)
	  at org.ehcache.CacheManager$close$0.call(Unknown Source:-1)
	  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	  at com.terracottatech.issues.EhcacheIssue.run(EhcacheIssue.groovy:14)
```

### LINKED ISSUE #1158: Implement timeout for clustered operations
Clustered cache operations can stall when a cluster server is unavailable to process the operation.  For `get`, this is probably not the right behavior.  This issue is opened to investigate the impact of adding a timeout to server communication.

### PR DESCRIPTION
**Pull request by cljohnso**
This commit introduces operation timeouts to Ehcache for control of the
time permitted for clustered operations.  One timeout is exposed through
configuration -- a GET operation timeout.  The other timeouts are either
internal or experimental.

In general, EhcacheClientEntity is changed to support timeouts for get,
mutative, and lifecycle operations.  When a timeout is recognized, a
TimeoutException is thrown from the EhcacheClientEntity.  (This commit
also removes a stall related to replicated operations.)

ServerStore methods, including those of ServerStoreProxy and its
subclasses, re-throw a TimeoutException caught from EhcacheClientEntity.

The ClusteredStore implementation is changed to throw a
StoreAccessTimeoutException when a TimeoutException is raised for a
mutative operation.  The StoreAccessTimeoutException is a
and RuntimeException bypasses the ResilienceStrategy in place for the
cache.  For get operations, ClusteredStore returns a 'null'.

Lifecycle operations performed by EhcacheClientEntityFactory and
EhcacheClientEntity are changed to throw a TimeoutException.  Changes
to DefaultClusteringService re-throw the TimeoutException as a
RuntimeException or another exception appropriate for the operation.

Merging this PR closes #1158 and fixes #1108.

### CODE REVIEW

**Comment by cljohnso** [comment]
Merging this PR closes #1158 and fixes #1108.

File: clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParserTest.java [hunk 1]
```diff
@@ -77,4 +109,218 @@ public void testSchema() throws Exception {
...
+            "  </ehcache:service>",
+            "",
+            "</ehcache:config>"
+        };
+
+    try {
+      new XmlConfiguration(makeConfig(config));
+      fail("Expecting XmlConfigurationException");
+    } catch (XmlConfigurationException e) {
+      e.printStackTrace();
```
Comment (cljohnso) [inline clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParserTest.java]: This shouldn't be here ...

**Comment by cljohnso** [comment]
Not that the `TerminatedServerTest` suite now takes about 2 minutes to run.  This is due partly to the startup/shutdown costs involved with external cluster servers and partly due to the timeout operations being tested.

**Comment by cljohnso** [comment]
Rebase and minor updates

**Comment by cljohnso** [comment]
A timing issue involving Galvan, terminating a server, and `start-tc-server.sh` is causing tests in this PR to fail.  Issue Terracotta-OSS/terracotta-core#237 is opened to address it.

**Comment by cljohnso** [comment]
Rebased and disabled a test pending update to #1219.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java [hunk 2]
```diff
@@ -111,6 +169,15 @@ public ServerSideConfiguration getServerConfiguration() {
     return serverConfiguration;
   }
 
+  /**
+   * The timeout for cache read operations.
+   *
+   * @return the cache read operation timeout; may be {@code null}
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java]: It may be null, but it doesn't say what null means.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+package org.ehcache.clustered.client.config;
+
+import java.math.BigInteger;
+import java.util.concurrent.TimeUnit;
+
+/**
+ * Describes a timeout value for a clustered operation.  Instances of this class
+ * are subject to the operation of the Java {@code java.util.concurrent.TimeUnit} class.
+ */
+public final class TimeoutDuration {
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: Timeout and Duration feel like words that are in opposition... this gives this class a strange feeling: TimeoutDuration.NONE for example.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+    } else {
+      /*
+       * Select the more precise/granular unit for the basis of the equals comparison. Since
+       * TimeUnit.convert _truncates_ fractional values, attempting to convert one a more
+       * precise/granular unit to a less precise/granular unit will result in zero -- indicating
+       * which is the more precise/granular unit.
+       */
+      TimeoutDuration lessGranular;
+      TimeoutDuration moreGranular;
+      if (this.unit.convert(1, that.unit) > 0) {
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: Enums are comparable... and TimeUnit is sensibly ordered... so you can just compare the enum instances directly.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+
+  private TimeoutDuration(long amount, TimeUnit unit) {
+    this.amount = amount;
+    this.unit = unit;
+  }
+
+  /**
+   * Constant indicating no timeout.
+   */
+  public static final TimeoutDuration NONE = new TimeoutDuration(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: This currently means that I can define legal durations longer than "NONE", isn't that a bit strange?

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java [hunk 6]
```diff
@@ -58,11 +67,110 @@ public ServerSideConfigurationBuilder autoCreate() {
...
+    public TimeoutDuration getReadOperationTimeout() {
+      return readOperationTimeout;
+    }
+  }
+
+  /**
+   * The client-side portion of the {@link ClusteringServiceConfiguration} used during
+   * configuration building.
+   */
+  interface ClusteringServiceClientSideConfiguration {
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java]: We can just eliminate this interface right?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 7]
```diff
@@ -250,4 +301,129 @@ private EhcacheEntityResponse invokeInternal(EhcacheEntityMessage message, boole
...
+          ", lifecycleOperationTimeout=" + lifecycleOperationTimeout +
+          '}';
+    }
+
+    /**
+     * Constructs instances of {@link Timeouts}.  When obtained from
+     * {@link Timeouts#builder()}, the default values are pre-set.
+     */
+    public static final class Builder {
+      private TimeoutDuration readOperationTimeout = TimeoutDuration.of(5, TimeUnit.SECONDS);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: I thought we had decided that the default timeout would be `NONE`?  In any case, if we are to have a default I think it would be better if it's sourced from the config code (as much as is practical).

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 8]
```diff
@@ -250,4 +301,129 @@ private EhcacheEntityResponse invokeInternal(EhcacheEntityMessage message, boole
...
+        if (readOperationTimeout == null) {
+          throw new NullPointerException("readOperationTimeout");
+        }
+        this.readOperationTimeout = readOperationTimeout;
+        return this;
+      }
+
+      /**
+       * Sets the timeout for mutative operations like {@code put} and {@code remove}.  The default value
+       * for this timeout is {@code Long.MAX_VALUE} nanoseconds.
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Is this meant to be TimeoutDuration.NONE?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 9]
```diff
@@ -250,4 +301,129 @@ private EhcacheEntityResponse invokeInternal(EhcacheEntityMessage message, boole
...
+        if (mutativeOperationTimeout == null) {
+          throw new NullPointerException("mutativeOperationTimeout");
+        }
+        this.mutativeOperationTimeout = mutativeOperationTimeout;
+        return this;
+      }
+
+      /**
+       * Sets the timeout for server store manager lifecycle operations like {@code validate} and {@code validateCache}.
+       *
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: What's the default value?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java [hunk 10]
```diff
@@ -98,6 +108,7 @@ public void create(final String identifier, final ServerSideConfiguration config
             try {
               EhcacheClientEntity entity = ref.fetchEntity();
               try {
+                entity.setTimeouts(entityTimeouts);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java]: Could this be moved inside the configure method?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java [hunk 11]
```diff
@@ -140,6 +166,7 @@ public EhcacheClientEntity retrieve(String identifier, ServerSideConfiguration c
        */
       boolean validated = false;
       try {
+        entity.setTimeouts(entityTimeouts);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java]: Like above, could we move this inside the validate method?  (and possibly change the name of that method as a result)

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java [hunk 12]
```diff
@@ -84,24 +91,22 @@ public URI getNamespace() {
...
   @Override
   public ServiceCreationConfiguration<ClusteringService> parseServiceCreationConfiguration(final Element fragment) {
-    /*
-     * The presumptions in this code are:
-     *   1) the Element is schema-validated
-     *   2) 'connection' is defined as required (minOccurs=1, maxOccurs=1)
-     *   3) 'connection.url' is defined as "required"
-     *   4) no other elements or attributes are defined
-     */
+
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java]: Are these presumption no longer true?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java [hunk 13]
```diff
@@ -117,11 +122,15 @@ public URI getNamespace() {
             } catch (URISyntaxException e) {
               throw new XmlConfigurationException(
                   String.format("Value of %s attribute on XML configuration element <%s> in <%s> is not a valid URI - '%s'",
-                      urlAttribute.getName(), fragment.getTagName(),
-                      (fragment.getParentNode() == null ? "null" : fragment.getParentNode().getLocalName()),
-                      connectionUri), e);
+                      urlAttribute.getName(), item.getNodeName(), fragment.getTagName(), connectionUri), e);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java]: Was this code broken?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java [hunk 14]
```diff
@@ -148,6 +161,29 @@ public URI getNamespace() {
         fragment.getTagName(), (fragment.getParentNode() == null ? "null" : fragment.getParentNode().getLocalName())));
   }
 
+  private TimeoutDuration processGetTimeout(Element parentElement, Node timeoutNode) {
+    TimeoutDuration getTimeout;
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java]: No need for this local variable.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java [hunk 15]
```diff
@@ -327,6 +361,10 @@ public void destroy(String name) throws CachePersistenceException {
       }
     } catch (ClusteredTierException e) {
       throw new CachePersistenceException("Unable to create clustered tier proxy '" + cacheIdentifier.getId() + "' for entity '" + entityIdentifier + "'", e);
+    } catch (TimeoutException e) {
+      throw new CachePersistenceException("Unable to create clustered tier proxy '"
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java]: Can't we have two catch blocks and thereby avoid the boolean?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java [hunk 16]
```diff
@@ -349,6 +386,13 @@ public void releaseServerStoreProxy(ServerStoreProxy storeProxy) {
       this.entity.releaseCache(cacheId);
     } catch (ClusteredTierReleaseException e) {
       throw new IllegalStateException(e);
+    } catch (TimeoutException e) {
+      /*
+       * A delayed ServerStore release is simply logged. If due to a disconnection, the server-side
+       * release will take place when the server recognizes the client is disconnected.  If the
+       * communication is only delayed, the message will eventually be presented and acted upon.
+       */
+      LOGGER.warn("Timed out trying to release clustered tier proxy for '{}'", cacheId, e);
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java]: This is true... but why is that a reason to swallow?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java [hunk 17]
```diff
@@ -407,7 +433,12 @@ public void clear() throws StoreAccessException {
     if(mappingFunction instanceof Ehcache.GetAllFunction) {
       Map<K, ValueHolder<V>> map  = new HashMap<K, ValueHolder<V>>();
       for (K key : keys) {
-        V value = getInternal(key);
+        V value;
+        try {
+          value = getInternal(key);
+        } catch (TimeoutException e) {
+          value = null;
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java]: This makes me uncomfortable... are we sure it's okay?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/NoInvalidationServerStoreProxy.java [hunk 18]
```diff
@@ -52,10 +53,12 @@ public boolean removeInvalidationListener(InvalidationListener listener) {
   }
 
   @Override
-  public Chain get(long key) {
+  public Chain get(long key) throws TimeoutException {
     EhcacheEntityResponse response;
     try {
       response = entity.invoke(messageFactory.getOperation(key), false);
+    } catch (TimeoutException e) {
+      throw e;
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/NoInvalidationServerStoreProxy.java]: Bleagh... I guess this is our best option here.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java [hunk 19]
```diff
@@ -122,6 +122,7 @@ public void onResponse(EhcacheEntityResponse.ClientInvalidateHash response) {
             entity.invoke(messageFactory.clientInvalidationAck(invalidationId), true);
           } catch (Exception e) {
             //TODO: what should be done here?
+            // TODO: TimeoutException possible -- is that significant here?
```
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java]: Would be nice to get this answered before merging.

File: xml/src/main/java/org/ehcache/xml/Conversions.java [hunk 20]
```diff
@@ -0,0 +1,59 @@
...
+  }
+
+  /**
+   * Converts {@link org.ehcache.xml.model.TimeUnit} to Java {@link TimeUnit}.
+   *
+   * @param unit the XML model time unit to convert
+   *
+   * @return the Java {@code TimeUnit} corresponding to {@code unit}
+   */
+  public static TimeUnit toJavaTimeUnit(org.ehcache.xml.model.TimeUnit unit) {
```
Comment (chrisdennis) [inline xml/src/main/java/org/ehcache/xml/Conversions.java]: If we're moving this to allow you to reuse core parsing logic, maybe other core parsing logic should be similarly exposed.  Also maybe we should use these methods to encapsulate the JAXB usage as well?

**Comment by chrisdennis** [comment]
test this please

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java (hunk 3 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: As discussed -- I'll do another PR to move `TimeoutDuration` into the API module under another name to be chosen -- maybe `TimeSpan` -- along with a new method in `org.ehcache.xml.Conversions` (or maybe another utility class like `Parser`) to support JAXB parsing of one from the JAXB `TimeUnit`.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java (hunk 4 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: Unfortunately, `TimeUnit` doesn't document that ordering so it's not part of the `TimeUnit` API  -- that's why I went the way I did.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java (hunk 5 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/TimeoutDuration.java]: True, but from a human or system up-time perspective anything involving `Long.MAX_VALUE` is "forever" which, in a timeout sense, is none.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java (hunk 6 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java]: We could go back to `ServerSideConfigurationBuilder` having to be aware of all of the properties in  `ClusteringServiceConfigurationBuilder`.  We could pass around the `ClusteringServiceConfigurationBuilder` instance instead ... thoughts?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java (hunk 7 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Let's chat about this one ... a conversation with Louis suggested a short get/read timeout, a not-as-short lifecycle timeout and no mutative timeout as default.  Right now, none of the configuration code is aware of the lifecycle and mutative operation timeouts -- there is limited (but necessary) exposure in `DefaultClusteringService` but `EhcacheClientEntity` is fully aware of those timeouts -- so that's there the default values are "managed".  There's at least one TODO regarding where to determine the default timeout for get/read operations.

File: clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java (hunk 6 above)
Comment (chrisdennis) [inline clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java]: Can't we just make the single static inner implementation of this package-private and use that directly without bothering with the interface?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java (hunk 10 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java]: Could be passed as a parameter to `configure` (and `validate`) ... is that what you'd prefer?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java (hunk 11 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java]: See comment on `configure`.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java (hunk 19 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java]: Changed `invoke` to `invokeAsync` -- no `TimeoutException`.

**Comment by henri-tremblay** [comment]
@cljohnso What would be the conditions to move the experimental timeouts to mainstream? They seem meaningful and are quite complex to configure right now.
