### PR TITLE
Fix #2204 : Handle empty chains that may get replicated

### LINKED ISSUE #2204: IndexOutOfBoundException during passive replication application
`ChainReplicationMessage.getResult()` behaves badly when the chain it's being asked to replicate is empty.  This can happen when there are multiple clients accessing the system due to cross segment eviction.  There are a number of ways of fixing this, and there is also some overdue yak shaving that can occur in this area.

### PR DESCRIPTION
**Pull request by rkavanap**
Empty chains may get replicated due to possibility of eviction between calls on the active.

### CODE REVIEW

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+import org.terracotta.testing.rules.Cluster;
+
+import java.io.File;
+import java.util.Arrays;
+import java.util.concurrent.CompletableFuture;
+
+import static org.terracotta.testing.rules.BasicExternalClusterBuilder.newCluster;
+
+public class OversizedCacheOpsPassiveTest extends ClusteredTests {
+  private static final int MAX_PUTS = 200;
```
Comment (rkavanap) [inline clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: To consistently reproduce the problems, MAX_PUTS have to be 10000 and MAX_SWITCH_OVERS have to be > 10, But that will cause delays in test execution. So for now they have been reduced.

**Comment by rkavanap** [comment]
@chrisdennis , I was able to consistently reproduce empty chains getting replicated..But I am unable to get an oversizedmapping exception.. Will keep trying..

However, with a code trick (e.g on an empty chain making storage engine return null), I was able to simulate an oversizedmapping exception on the passive which crashed the passive...Since this was not a valid case that can happen (esp. since put will not pass empty chains down), I am not doing any special handling for oversizedmapping exception on passive yet...We could simply do a catch on oversizedmapping exception and log an error for now in the clustered tier passive entity. wdyt?

File: clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java [hunk 2]
```diff
@@ -80,6 +80,10 @@ public void replaceAtHead(long key, Chain expect, Chain update) {
   }
 
   public void put(long key, Chain chain) {
+    if (chain.isEmpty()) {
+      // holes may exist where empty chains may be replicated..just return in such cases
```
Comment (chrisdennis) [inline clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: Should a put of an empty chain map to a remove?  Seems odd to leave existing state in place?

Comment (rkavanap) [reply clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java]: ok.

**Comment by rkavanap** [comment]
test this please

**Comment by rkavanap** [comment]
Already merged through another PR..closing this

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+  private static final String RESOURCE_CONFIG =
+      "<config xmlns:ohr='http://www.terracotta.org/config/offheap-resource'>"
+      + "<ohr:offheap-resources>"
+      + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">2</ohr:resource>"
+      + "</ohr:offheap-resources>" +
+      "</config>\n";
+
+  @ClassRule
+  public static Cluster CLUSTER =
+      newCluster(2).in(new File("build/cluster"))
```
[the remark this answers is not in the document]
Comment (rkavanap) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: you are right..we should ideally use.. Paths.get("build", "cluster")...However, this works on windows..all tests follow this pattern..Did not want to change it just for this..

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+  private void doPuts(CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder) {
+    try (PersistentCacheManager cacheManager = clusteredCacheManagerBuilder.build(true)) {
+      CacheConfiguration<Long, String> config = CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
+        ResourcePoolsBuilder.newResourcePoolsBuilder()
+          .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 2, MemoryUnit.MB)))
+        .build();
+      Cache<Long, String> cache = cacheManager.createCache("clustered-cache", config);
+      for (long i = 0; i < MAX_PUTS; i++) {
+        if (i % 100 == 0) {
+          Thread.yield(); Thread.yield(); Thread.yield();
```
[the remark this answers is not in the document]
Comment (rkavanap) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: just creating a small pause here without sleep...also helps on a uniprocessor machine, other put thread gets a chance..although that is not a strong argument as put call is io intensive.

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+
+    CompletableFuture f1 = CompletableFuture.runAsync(() -> doPuts(clusteredCacheManagerBuilder));
+    CompletableFuture f2 = CompletableFuture.runAsync(() -> doPuts(clusteredCacheManagerBuilder));
+
+    for (int i = 0; i < MAX_SWITCH_OVER; i++) {
+      CLUSTER.getClusterControl().terminateActive();
+      CLUSTER.getClusterControl().waitForActive();
+      CLUSTER.getClusterControl().startOneServer();
+      CLUSTER.getClusterControl().waitForRunningPassivesInStandby();
+      Thread.sleep(100);
```
[the remark this answers is not in the document]
Comment (rkavanap) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: ..sleep gives some small window where some puts happen when no sync is happening..

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+  private static final int MAX_SWITCH_OVER = 3;
+
+  private static final String RESOURCE_CONFIG =
+      "<config xmlns:ohr='http://www.terracotta.org/config/offheap-resource'>"
+      + "<ohr:offheap-resources>"
+      + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">2</ohr:resource>"
+      + "</ohr:offheap-resources>" +
+      "</config>\n";
+
+  @ClassRule
```
[the remark this answers is not in the document]
Comment (rkavanap) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: @henri-tremblay I have incorporated all other comments except this. Since cluster startup is expensive, it is better if someone adds a test in the future we are not accidentally starting the cluster every time just because that person forgot to change this to a class rule later..Also the framework of this test class should allow more tests to be added without having to again refactor stuff.

**Comment by rkavanap** [comment]
test this please

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+  public static Cluster CLUSTER =
+      newCluster(2).in(Paths.get("build", "cluster").toFile())
+        .withSystemProperty("ehcache.sync.data.gets.threshold", "2")
+        .withServiceFragment(RESOURCE_CONFIG)
+        .build();
+
+  @BeforeClass
+  public static void waitForServers() throws Exception {
```
Comment (rkavanap) [inline clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: @chrisdennis I had to do a waitForServers for this test case because otherwise the terminateActive that happens immediately in the test is taking platform through different paths which is not the purpose of this test, On slow build machines, this is making the core hit different windows.

**Comment by rkavanap** [comment]
test this please

**Comment by rkavanap** [comment]
@henri-tremblay Can you approve and merge, please?

File: clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java (hunk 7 above)
Comment (chrisdennis) [reply clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java]: Okay - makes sense.
