### PR TITLE
Closes #1593 Avoid response listener registration race during store creation

### LINKED ISSUE #1593: One of the Ehcache client waits until other completes
In Strong consistency mode, one of the Ehcache client hangs until the other completes during mutations (seen with put,putIfAbsent and replace operations so far)
Waiting client continues once other client is completed.

1. Start  Active and Passive servers
2. Start two clients in strong consistency mode doing mutation (issue seen with put/replace<K,V>/putIfAbsent operations so far)

````
PersistentCacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(CLUSTER_URI)
            .autoCreate()
            .defaultServerResource("primary-server-resource")
            .resourcePool("resource-pool-a", 128, MemoryUnit.KB)
            .resourcePool("resource-pool-b", 128, MemoryUnit.KB, "secondary-server-resource"))
        .withCache("clustered-cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 256, MemoryUnit.MB)))
            .add(new ClusteredStoreConfiguration(Consistency.STRONG))).build(true);


    Cache cache1 = cacheManager.getCache("clustered-cache1", Long.class, String.class);


    for (long i = 0; i < 20000; i++) {
      cache1.put(i, "hello" + i);
    }
````

One of the client waits until other completes (continues after other client is done), stack trace as below

````

"main" #1 prio=5 os_prio=0 tid=0x00000000021bd000 nid=0x3428 waiting on condition [0x00000000023fc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076f2e5f40> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.awaitOnLatch(StrongServerStoreProxy.java:260)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.performWaitingForHashInvalidation(StrongServerStoreProxy.java:200)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.getAndAppend(StrongServerStoreProxy.java:309)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.replace(ClusteredStore.java:347)
	at org.ehcache.core.Ehcache.replace(Ehcache.java:520)
	at com.terracotta.qa.ehcache.ApCrudTest.testCrudOperations(ApCrudTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:58)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

````

### PR DESCRIPTION
**Pull request by albinsuresh**
Apart from fixing the bug, I have left some of the log statements in different classes  that I used to debug the issue. Most of those are at debug/trace level. Will extend similar logging to the rest of the code base if this is approved.

### CODE REVIEW

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 1]
```diff
@@ -90,7 +90,7 @@
   private final LifeCycleMessageFactory messageFactory;
   private final Map<Class<? extends EhcacheEntityResponse>, List<ResponseListener<? extends EhcacheEntityResponse>>> responseListeners = new ConcurrentHashMap<Class<? extends EhcacheEntityResponse>, List<ResponseListener<? extends EhcacheEntityResponse>>>();
   private final List<DisconnectionListener> disconnectionListeners = new CopyOnWriteArrayList<DisconnectionListener>();
-  private final List<ReconnectListener> reconnectListeners = new ArrayList<ReconnectListener>();
+  private final List<ReconnectListener> reconnectListeners = new CopyOnWriteArrayList<ReconnectListener>();
```
Comment (albinsuresh) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: I'm still not sure if the old way of using the `ArrayList` and synchronizing every access is better over the use of this `CopyOnWriteArrayList`. Did that anyway so that it's consistent with the other listeners. Is there gonna any significant performance difference? Which one is preferred?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java [hunk 2]
```diff
@@ -80,7 +80,7 @@
 
   private volatile Connection clusterConnection;
   private EhcacheClientEntityFactory entityFactory;
-  private EhcacheClientEntity entity;
+  EhcacheClientEntity entity;
```
Comment (albinsuresh) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java]: Did that for testability. Not sure if it's a good practice to expose the visibility of a member field just for testing purposes. Is accessing this field using reflection preferred over this approach?

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxy.java [hunk 3]
```diff
@@ -104,6 +106,13 @@ public boolean removeInvalidationListener(InvalidationListener listener) {
   }
 
   @Override
+  public void close() {
+    this.entity.removeResponseListener(EhcacheEntityResponse.ServerInvalidateHash.class);
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxy.java]: See my other comment on the method declaration - this is wrong as soon as you have more than one clustered cache in a cache manager.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java (hunk 1 above)
Comment (albinsuresh) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Discussed with @AbfrmBlr and the reason it was done with synchronised was not just for visibility but to make every access to that list exclusive. Even iteration over that list has to be exclusive with other mutations. This exclusiveness is required to avoid listener registration/deregistartion races while a reconnect is happening (iteration over the listeners). So reverting this change.

**Comment by albinsuresh** [comment]
Addressed the review comments

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java (hunk 1 above)
Comment (AbfrmBlr) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Nope i.e. not the reason. Let me explain it again, it is to keep store creation on hold while reconnect data is being formed. CopyWrite does provides immutable data, so its not about exclusive access. The Store completion at client side creates store at server side, and then registers the listeners(kind of two step process).So reconnect can interleave during cache creatio itself. With CopyOnWrite, listener registration will complete in middle of reconnect data being formed, and cache can theoretically start doing operations which is absent in reconnect data.Though with eventual invalidation accounting on the server side, this may be rare with strong caches, but for now I would suggest to leave it with sync so that its easier to reason about it. IMHO, disconnection listener registration/deregistraion should also be revisited w.r.t. to     race with didDisconnectUnexpectedly event being fired.
