### PR TITLE
Fix #1534

### LINKED ISSUE #1534: Demo 01-CacheAside throws an exception at startup
We get the following exception:

	org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'java.util.List'
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.getSerializerClassFor(DefaultSerializationProvider.java:137) ~[main/:na]
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createSerializer(DefaultSerializationProvider.java:99) ~[main/:na]
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createValueSerializer(DefaultSerializationProvider.java:91) ~[main/:na]
	        at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:256) [main/:na]
	        at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:390) [main/:na]
	        at org.ehcache.demos.peeper.DataCache.setupCache(DataCache.java:35) [main/:na]
	        at org.ehcache.demos.peeper.DataStore.init(DataStore.java:44) [main/:na]
	        at org.ehcache.demos.peeper.PeeperServletContextListener.contextInitialized(PeeperServletContextListener.java:31) [main/:na]

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

File: impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java [hunk 1]
```diff
@@ -80,10 +79,10 @@
 import static org.ehcache.config.ResourceType.Core.OFFHEAP;
 import static org.ehcache.config.builders.ResourcePoolsBuilder.newResourcePoolsBuilder;
 import static org.ehcache.core.internal.service.ServiceLocator.dependencySet;
+import static org.ehcache.core.internal.service.ServiceLocator.findSingletonAmongst;
```
Comment (ljacomet) [inline impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java]: Could you make sure your IDE does not go wild in re-ordering imports when you are not touching them?

File: impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java [hunk 2]
```diff
@@ -268,7 +267,8 @@ public void close() throws Exception {
         if (resources.contains(OFFHEAP) || resources.contains(DISK)) {
           throw new RuntimeException(e);
         } else {
-          LOGGER.debug("Could not create serializers for user managed cache {}", id, e);
+          // It doesn't matter if we didn't find it for heap because we will probably not need it
+          LOGGER.debug("Could not create serializers for user managed cache '{}': {}", id, e.getMessage());
```
Comment (ljacomet) [inline impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java]: I would append that info to the logged message instead of having a comment (soon to be stale) before it.

File: impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java (hunk 1 above)
Comment (henri-tremblay) [inline impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java]: Yes. I noticed. But they are in the right other now. Do you prefer to leave them unordered?

File: impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java (hunk 2 above)
Comment (henri-tremblay) [inline impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java]: I thought about it but felt the log would be too long. But ok, let's do it.

Comment (henri-tremblay) [inline impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java]: Done

**Comment by AbfrmBlr** [comment]
test this please

**Comment by ljacomet** [comment]
test this please
