### PR TITLE
Closes #1279 Limit EhcacheEntityResponse.Failure to return ClusteredEhcacheException

### LINKED ISSUE #1279: Limit EhcacheEntityResponse.Failure to return ClusteredEhcacheException
The `EhcacheEntityResponse.Failure` message is used to return a server-thrown exception.  The message is presently set up to accept any `Exception` which then needs to be re-interpreted on the client to add the client context (most importantly, stack trace).  Updates for issue #1256 adds a method specifically for the adding the client-side stack trace to `ClusteredEhcacheException` instances.  From an error handling hygiene point of view, it would be best to have _only_ `ClusteredEhcacheException` subclasses returned forcing server code to return exceptions that can be more directly re-thrown in the client (or provide more contextual detail for other client-side handling).

### PR DESCRIPTION
**Pull request by albinsuresh**

### CODE REVIEW

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java [hunk 1]
```diff
@@ -316,8 +317,13 @@ public void destroy(String name) throws CachePersistenceException {
         try {
           this.entity.validateCache(cacheId, clientStoreConfiguration);
         } catch (ClusteredTierValidationException ex) {
-          if (ex.getCause() instanceof InvalidStoreException) {
-            this.entity.createCache(cacheId, clientStoreConfiguration);
+          if(ex.getCause() instanceof ClusteredClientException) {
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java]: The wrapping / unwrapping that leads to these `instanceof` checks are a design smell IMO

**Comment by lorban** [comment]
Why have you moved the server exceptions from `org.ehcache.clustered.common` into `org.ehcache.clustered.server` in the server module? This way, the client doesn't have access to the server exceptions and will fail to deserialize them.

**Comment by lorban** [comment]
There seems to be some overlap with #1256. Both PRs should be aligned, you'll probably want to speak with @cljohnso about this.

**Comment by albinsuresh** [comment]
Was wondering the same. With the split done into client and server side exceptions and the way server side exceptions are wrapped in a client side exception, #1256 will be resolved.

**Comment by albinsuresh** [comment]
I request reviewers to look at the last commit separately and tell me if it doesn't make sense.

**Comment by cljohnso** [comment]
Blocked pending resolution with issue  #1256 / PR #1272.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 2]
```diff
@@ -143,48 +144,48 @@ public void close() {
...
+      throw new ClusteredTierManagerValidationException("Error validating server clustered tier manager", e.getCause());
     }
   }
 
   public void configure(ServerSideConfiguration config) throws ClusteredTierManagerConfigurationException {
     try {
       invokeInternal(messageFactory.configureStoreManager(config), true);
-    } catch (Exception e) {
-      throw new ClusteredTierManagerConfigurationException("Error configuring clustered tier manager", e);
+    } catch (ClusteredClientException e) {
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: This is very wrong - we end up wrapping a server exception in a client exception to unwrap it immediately and rewrap before throwing.

**Comment by ljacomet** [comment]
Unblocking following comments on the #1279

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 3]
```diff
@@ -256,11 +244,7 @@ private EhcacheEntityResponse invokeInternal(TimeoutDuration timeLimit, EhcacheE
          * elements.  The server-side exception must be wrapped in a client-side exception
          * to provide proper stack trace for analysis.
          */
-        Exception cause = ((Failure)response).getCause();
-        if (cause instanceof ClusteredEhcacheException) {
-          throw ((ClusteredEhcacheException) cause).withClientStackTrace();
-        }
-        throw new RuntimeException(message + " error: " + cause.toString(), cause);
+        throw ((Failure)response).getCause().withClientStackTrace();
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Why not push that `withClientStackTrace()` into the `Response.decode` method directly?

Comment (albinsuresh) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Sure.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 4]
```diff
@@ -256,11 +244,7 @@ private EhcacheEntityResponse invokeInternal(TimeoutDuration timeLimit, EhcacheE
          * elements.  The server-side exception must be wrapped in a client-side exception
          * to provide proper stack trace for analysis.
          */
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: That comment is no longer relevant since it happens inside the codec
