### PR TITLE
Closes #2451 - ignore unresolvable optional dependencies that are present on the classpath

### LINKED ISSUE #2451: Regression between 3.5.2 and master : Failed to find provider with satisfied dependency set for interface
I used to be able to run such code with 3.5.2 : 

```
DefaultManagementRegistryConfiguration managementRegistryConfiguration = new DefaultManagementRegistryConfiguration()
        .setCacheManagerAlias(CM_NAME);
DefaultManagementRegistryService managementRegistry = new DefaultManagementRegistryService(managementRegistryConfiguration);
    managementRegistryConfiguration.addTags("pif", "paf", "pouf");

    CacheManagerBuilder cacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
        .using(managementRegistry);
    CacheManager cacheManager = cacheManagerBuilder.build();

```

Now, (current master), it will throw when ```cacheManagerBuilder.build()``` is called: 

```
Exception in thread "main" java.lang.IllegalStateException: org.ehcache.core.internal.service.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.clustered.client.service.EntityService [candidates []]
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.build(ServiceLocator.java:321)
	at org.ehcache.core.EhcacheManager.resolveServices(EhcacheManager.java:146)
	at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:119)
	at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:109)
	at org.ehcache.config.builders.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:114)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:70)
	at AnthonyClient.start(AnthonyClient.java:107)
	at AnthonyClient.main(AnthonyClient.java:47)
Caused by: org.ehcache.core.internal.service.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.clustered.client.service.EntityService [candidates []]
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.lookupService(ServiceLocator.java:363)
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.lookupDependenciesOf(ServiceLocator.java:327)
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.build(ServiceLocator.java:302)
	... 7 more
```

### PR DESCRIPTION
**Pull request by lorban**
This is the simplest way I've found to ignore optional dependencies.

### CODE REVIEW

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java [hunk 1]
```diff
@@ -324,7 +325,16 @@ public ServiceLocator build() {
 
     ServiceMap lookupDependenciesOf(ServiceMap resolved, Class<? extends Service> requested) throws DependencyException {
       for (Class<? extends Service> dependency : identifyImmediateDependenciesOf(requested)) {
-        resolved = lookupService(resolved, dependency);
+        try {
```
Comment (henri-tremblay) [inline core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: I'm fine with the general concept. The thing I don't get is why blending normal dependencies and optional ones. They could be resolved separately: `identifyImmediateDependenciesOf` and `identifyImmediateOptionalDependenciesOf`. With the exception check only on the later. This is not directly the code of this PR. It is a quirk in the original code. The PR just makes it more obvious.

**Comment by anthonydahanne** [comment]
I'm cool with the changes and the tests too.
Let me run that locally with my sample code

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java (hunk 1 above)
Comment (lorban) [reply core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: I've refactored the code to introduce `identifyImmediateOptionalDependenciesOf` but I do find the code less readable.

But I'll leave it up to you which form you prefer.

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java [hunk 2]
```diff
@@ -425,9 +438,28 @@ ServiceMap lookupDependenciesOf(ServiceMap resolved, Class<? extends Service> re
...
+      }
+    }
+
+    dependencies.addAll(identifyImmediateDependenciesOf(clazz.getSuperclass()));
+
+    return dependencies;
+  }
+
+  private static Set<Class<? extends Service>> identifyImmediateOptionalDependenciesOf(final Class<?> clazz) {
+    if (clazz == null) {
```
Comment (henri-tremblay) [inline core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: Why would clazz be null?

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java [hunk 3]
```diff
@@ -326,6 +327,18 @@ ServiceMap lookupDependenciesOf(ServiceMap resolved, Class<? extends Service> re
       for (Class<? extends Service> dependency : identifyImmediateDependenciesOf(requested)) {
         resolved = lookupService(resolved, dependency);
       }
+      for (Class<? extends Service> dependency : identifyImmediateOptionalDependenciesOf(requested)) {
+        try {
+          resolved = lookupService(resolved, dependency);
+        } catch (DependencyException de) {
```
Comment (henri-tremblay) [inline core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: My idea was to move the try/catch inside identifyImmediateOptionalDependenciesOf

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java (hunk 2 above)
Comment (lorban) [reply core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: Go figure. It's present in `identifyImmediateDependenciesOf` so I kept it in `identifyImmediateOptionalDependenciesOf` too. Better be safe than sorry.

Comment (henri-tremblay) [reply core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: Hum... Recursion I guess

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java (hunk 3 above)
Comment (lorban) [reply core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: That can't be done with the way the code currently is structured as you can only know if an optional dependency can be resolved or not when it is being looked up.

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java [hunk 4]
```diff
@@ -445,11 +477,11 @@ ServiceMap lookupDependenciesOf(ServiceMap resolved, Class<? extends Service> re
 
     for (Class<?> interfaceClazz : clazz.getInterfaces()) {
       if (Service.class.isAssignableFrom(interfaceClazz)) {
-        dependencies.addAll(identifyImmediateDependenciesOf(Service.class.getClass().cast(interfaceClazz)));
+        dependencies.addAll(identifyImmediateOptionalDependenciesOf(Service.class.getClass().cast(interfaceClazz)));
```
Comment (henri-tremblay) [inline core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: It feels like we could recurse over `lookupDependenciesOf` to prevent the code duplication between optional and not optional. Or keep the code mechanic and pass a lambda to have an optional/non-optional behavior.

File: core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java (hunk 3 above)
Comment (henri-tremblay) [reply core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java]: Ah... Not that useful then
