### PR TITLE
[release/3.3] Fix #2159 Proper support of StatefulSerializer in XAStore

### LINKED ISSUE #2159: XAStoreConfiguration gives NPE when adding a java serializable POJO
1.  Ehcache version :  3.4.0
2. Cache/CacheManager configuration : 
```java
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .using(new LookupTransactionManagerProviderConfiguration(
                BitronixTransactionManagerLookup.class))
            .withCache("xaCache",
                CacheConfigurationBuilder
                    .newCacheConfigurationBuilder(Long.class, Person.class,
                        ResourcePoolsBuilder.heap(Long.MAX_VALUE))
                    .withExpiry(Expirations.noExpiration()).add(new XAStoreConfiguration("xaCache"))
                    .build())
            .build();
```
JDK 1.8 and Windows 10. 

Sample code : 
```java
BitronixTransactionManager manager = TransactionManagerServices.getTransactionManager();
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .using(new LookupTransactionManagerProviderConfiguration(
                BitronixTransactionManagerLookup.class))
            .withCache("xaCache",
                CacheConfigurationBuilder
                    .newCacheConfigurationBuilder(Long.class, Person.class,
                        ResourcePoolsBuilder.heap(Long.MAX_VALUE))
                    .withExpiry(Expirations.noExpiration()).add(new XAStoreConfiguration("xaCache"))
                    .build())
            .build();
        cacheManager.init();

Cache<Long, Person> cc = cacheManager.getCache("xaCache", Long.class, Person.class);
        manager.begin();
        Person p = new Person("Sukhpal", 10);
        cc.put(1L, p);
        manager.commit();
```
Stacktrace : 

```
Caused by: org.ehcache.core.spi.store.StoreAccessException: java.lang.NullPointerException
	at org.ehcache.core.exceptions.StorePassThroughException.handleRuntimeException(StorePassThroughException.java:70)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:507)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:453)
	at org.ehcache.transactions.xa.internal.XATransactionContext.putIfAbsentInUnderlyingStore(XATransactionContext.java:296)
	at org.ehcache.transactions.xa.internal.XATransactionContext.prepare(XATransactionContext.java:154)
	at org.ehcache.transactions.xa.internal.XATransactionContext.commitInOnePhase(XATransactionContext.java:225)
	at org.ehcache.transactions.xa.internal.EhcacheXAResource.commit(EhcacheXAResource.java:69)
	... 10 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.ehcache.impl.serialization.CompactJavaSerializer.addMappingUnderLock(CompactJavaSerializer.java:165)
	at org.ehcache.impl.serialization.CompactJavaSerializer.getOrAddMapping(CompactJavaSerializer.java:149)
	at org.ehcache.impl.serialization.CompactJavaSerializer.access$000(CompactJavaSerializer.java:52)
	at org.ehcache.impl.serialization.CompactJavaSerializer$OOS.writeClassDescriptor(CompactJavaSerializer.java:200)
	at java.io.ObjectOutputStream.writeNonProxyDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeClassDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.ehcache.impl.serialization.CompactJavaSerializer.serialize(CompactJavaSerializer.java:94)
	at org.ehcache.transactions.xa.internal.XAValueHolder.copyForSerialization(XAValueHolder.java:79)
	at org.ehcache.transactions.xa.internal.SoftLock.copyForSerialization(SoftLock.java:68)
	at org.ehcache.transactions.xa.internal.SoftLockValueCombinedSerializer.serialize(SoftLockValueCombinedSerializer.java:42)
	at org.ehcache.transactions.xa.internal.SoftLockValueCombinedSerializer.serialize(SoftLockValueCombinedSerializer.java:30)
	at org.ehcache.impl.internal.store.heap.holders.SerializedOnHeapValueHolder.<init>(SerializedOnHeapValueHolder.java:41)
	at org.ehcache.impl.internal.store.heap.holders.SerializedOnHeapValueHolder.<init>(SerializedOnHeapValueHolder.java:49)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1542)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1535)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.newCreateValueHolder(OnHeapStore.java:1481)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.access$500(OnHeapStore.java:114)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$10.apply(OnHeapStore.java:476)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$10.apply(OnHeapStore.java:467)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend$3.apply(KeyCopyBackend.java:159)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend$3.apply(KeyCopyBackend.java:156)
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1878)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend.compute(KeyCopyBackend.java:156)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:467)
	... 15 common frames omitted
```

### PR DESCRIPTION
**Pull request by ljacomet**
The way the serializers were wired hid the fact that the underlying
Store may have to initialize a stateful one.

### CODE REVIEW

File: transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
 class SoftLockValueCombinedSerializer<T> implements Serializer<SoftLock<T>> {
 
   private final AtomicReference<? extends Serializer<SoftLock<T>>> softLockSerializerRef;
-  private final Serializer<T> valueSerializer;
+  final Serializer<T> valueSerializer;
```
Comment (henri-tremblay) [inline transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java]: Can be `protected` no?

Comment (ljacomet) [reply transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java]: What would be the point? It would become _more_ accessible.

**Comment by ljacomet** [comment]
@henri-tremblay Not too sure about the integration test. Feels like added build time for little value.

File: transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java (hunk 1 above)
Comment (henri-tremblay) [reply transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java]: Because we test that `init` is called now. But an integration test will prove that **it is** working. That no other issue is in the way.

**Comment by henri-tremblay** [comment]
Because we test that `init` is called now. But an integration test will prove that **it is** working. That no other issue is in the way.

File: transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java (hunk 1 above)
Comment (henri-tremblay) [reply transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java]: True... It is just my feeling. When something can be used by a parent class, I don't like to force the parent to be in the same package. But then you will say that the class is already in default scope... Which I missed... So keep it default scope :-)

**Comment by ljacomet** [comment]
Ok, will see what I can come up with and how much time it burns in the build.

**Comment by henri-tremblay** [comment]
Something like this would be fine with me:

```
public class StatefulTest {

  @Test
  public void test() throws Exception {
    BitronixTransactionManager manager = TransactionManagerServices.getTransactionManager();
    try(CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
      .using(new LookupTransactionManagerProviderConfiguration(
        BitronixTransactionManagerLookup.class))
      .withCache("xaCache",
        CacheConfigurationBuilder
          .newCacheConfigurationBuilder(Long.class, ArrayList.class,
            ResourcePoolsBuilder.heap(Long.MAX_VALUE))
          .withExpiry(Expirations.noExpiration()).add(new XAStoreConfiguration("xaCache"))
          .build())
      .build(true)) {

      @SuppressWarnings({"unchecked","rawtype"})
      Cache<Long, ArrayList<?>> cc = (Cache)
        cacheManager.getCache("xaCache", Long.class, ArrayList.class);
      manager.begin();
      cc.put(1L, new ArrayList<>());
      manager.commit();
    }
  }
}
```

**Comment by ljacomet** [comment]
@henri-tremblay Added integration test based on your suggestion
