### PR TITLE
Fix #1275 Improve error message for destroyCache

### LINKED ISSUE #1275: Add more intuitive exception message when invoked destroy on cache being used by other clients
Client version:
```ehcache-clustered
Implementation-Version: 3.1.0-SNAPSHOT 3d44aa4c4a3047b773beab6ee761262
 036491394
```

Server version:
```
Terracotta 5.0.0-beta2, as of 2016-06-30 at 01:31:45 PDT (Revision 94748627d9b6fb3e06e6ccad724f821ef1ef741d from UNKNOWN)
```

When called **cacheManager.destroyCache("clustered-cache")** from one client while there are other clients still using the "clustered-cache", below exception is hit. 

@AbfrmBlr mentioned this is the expected behavior as unless all the other clients using this cache are terminated and then the destroyCache called from a single client, this is expected to work.
If that is the case, then the exception message should be more explicitly saying this.

```
java.lang.AssertionError: Caught exception during execution
Expected: is null
     but: was <org.ehcache.StateTransitionException: Couldn't acquire cluster-wide maintenance lease>

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.terracotta.qa.ehcache.test.MultipleClientsTest.testCRUDOps(MultipleClientsTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:58)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

### PR DESCRIPTION
**Pull request by ljacomet**
When a cache cannot be destroyed because it is still in use, the
message was limited to the bottom cause. This makes it apparent from
the top of the exception hierarchy.
Also cleaned up tests related to destroyCache

### CODE REVIEW

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java [hunk 1]
```diff
@@ -202,6 +203,8 @@ public void releaseCache(String name) throws ClusteredTierReleaseException, Time
   public void destroyCache(String name) throws ClusteredTierDestructionException, TimeoutException {
     try {
       invokeInternal(timeouts.getLifecycleOperationTimeout(), messageFactory.destroyServerStore(name), true);
+    } catch (ResourceBusyException e) {
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Idea here is that this is a _valid_ outcome, not the result of messed up state server side. If we agree that catching these differently makes sense, I would probably revise a number of other locations in that same class.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java [hunk 2]
```diff
@@ -310,7 +310,7 @@ public void destroy(String name) throws CachePersistenceException {
     try {
       entity.destroyCache(name);
     } catch (ClusteredTierDestructionException e) {
-      throw new CachePersistenceException("Cannot destroy clustered tier '" + name + "' on " + clusterUri, e);
+      throw new CachePersistenceException(e.getMessage() + " (on " + clusterUri + ")", e);
```
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java]: Opinionated decision that the cluster information really belongs at the end of the underlying exception message.

File: clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java [hunk 3]
```diff
@@ -107,6 +107,16 @@ public void testDestroyFreesUpTheAllocatedResource() throws CachePersistenceExce
   }
 
   @Test
+  public void testDestroyUnknownCacheAlias() throws Exception {
+    clusteredCacheManagerBuilder.build(true).close();
+
+    PersistentCacheManager cacheManager = newCacheManagerBuilder().with(cluster(CLUSTER_URI).expecting()).build(true);
+
+    // No exception thrown here indicates it succeeded as other test show
+    cacheManager.destroyCache("clustered-cache");
```
Comment (chrisdennis) [inline clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java]: Could you assert that the destruction was successful somehow?

File: clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java [hunk 4]
```diff
@@ -691,7 +691,7 @@ private void destroyServerStore(ClientDescriptor clientDescriptor, DestroyServer
 
     final Set<ClientDescriptor> clients = storeClientMap.get(name);
     if (clients != null && !clients.isEmpty()) {
-      throw new ResourceBusyException("Can not destroy clustered tier '" + name + "': in use by " + clients.size() + " clients");
+      throw new ResourceBusyException("Cannot destroy clustered tier '" + name + "': in use by " + clients.size() + " other client(s)");
```
Comment (chrisdennis) [inline clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java]: I wonder what the `toString()` of a ClientDescriptor looks like?

File: clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java (hunk 3 above)
Comment (cljohnso) [inline clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java]: Not without doing some of the "nastiness" resorted to in `DefaultClusteringServiceTest` with the aid of `ObservableEhcacheServerEntityService`.

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java (hunk 1 above)
Comment (cljohnso) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: So you want to differentiate between a busy and a fault simply through the message in the `ClusteredTierDestructionException` being thrown?  For a busy, using a different exception would permit a program to delay for a bit and retry the destroy; re-using the `ClusteredTierDestructionException` makes that more of a challenge.

File: clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java (hunk 3 above)
Comment (chrisdennis) [inline clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java]: Can't we just try to retrieve the cache?  That should fail since we just destroyed it (assuming we use the right connection mode).

File: clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java (hunk 1 above)
Comment (ljacomet) [inline clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java]: Did not think of going that far. Anyway, what gets out of Ehcache is a `CachePersistenceException` so in the end,  does not matter too much. Was mostly saying that I would handle _valid_ outcomes specifically rather than in the general catch block below.

File: clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java (hunk 3 above)
Comment (ljacomet) [inline clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java]: Correct - will do that.

File: clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java (hunk 4 above)
Comment (ljacomet) [inline clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java]: From a quick look, not something that would help users.

**Comment by cljohnso** [comment]
I'm good with this ... @chrisdennis if you'd like to merge, please be my guest.

File: clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java (hunk 4 above)
Comment (chrisdennis) [inline clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java]: Should it?  I'm just thinking that if you see this exception: `Cannot destroy clustered tier 'foo': in use by 1 other client(s)` what can you do about it?  Seeing `Cannot destroy clustered tier 'foo': in use by Client[192.168.0.42:56789]` is much more actionable.

Comment (ljacomet) [inline clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java]: Agreed, but would like to split that change from what's done here then. @chrisdennis wdyt?

Comment (chrisdennis) [inline clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java]: Okay, file away.
