### PR TITLE
[master] Fix #1331 Invert invalid eviction prioritizer

### LINKED ISSUE #1331: On heap eviction prioritizer is inverted
As [reported on the users group](https://groups.google.com/forum/#!category-topic/ehcache-users/ehcache-core/OJdaVpQw6PU), we incorrectly evict the most recent element instead of the least recent.

A fix for this + basic tests making sure it never gets reintroduced are needed.

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

File: impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java [hunk 1]
```diff
@@ -128,7 +132,7 @@ public int compare(ValueHolder<?> t, ValueHolder<?> u) {
       } else if (u instanceof Fault) {
         return 1;
       } else {
-        return Long.signum(t.lastAccessTime(TimeUnit.NANOSECONDS) - u.lastAccessTime(TimeUnit.NANOSECONDS));
+        return Long.signum(u.lastAccessTime(TimeUnit.NANOSECONDS) - t.lastAccessTime(TimeUnit.NANOSECONDS));
```
Comment (chrisdennis) [inline impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java]: We should probably do:
```java
return -Long.compare(t.lastAccessTime(TimeUnit.NANOSECONDS), u.lastAccessTime(TimeUnit.NANOSECONDS));
```

Comment (ljacomet) [inline impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java]: Indeed - will adapt
